typography_spectrum: 0.5647119162604213
color:
  brandColors:
    - '#000000'
    - '#a4a4a2'
    - '#7c7c7a'
    - '#585856'
    - '#f5f5f5'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.856814773986116
analytics:
  google: null
  facebook: null
  twitter: null
name: Madikis Productions
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Music
    url: 'https://soundcloud.com/madikis'
    type: external
favicon: null
title: Madikis Productions
purpose: []
