name: Madikis Productions
favicon: null
layout_spectrum: 0.24233
typography_spectrum: 0.50768
title: Madikis Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#286987'
    - '#7d5c77'
    - '#5f98ab'
    - '#e4a9a1'
  brandStrength: 0.6725583313964307
  lightness: 0.5565290078520775
  saturation: 0.45107075083069503
  rhythmicContrast: 0.46708237030543387
purpose: []
