name: Madikis Productions
favicon: null
layout_spectrum: 0.25376
typography_spectrum: 0.50768
title: Madikis Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74a2aa'
    - '#e6ffe5'
    - '#3f5861'
    - '#1a2b3a'
    - '#010013'
  brandStrength: 0.5
  lightness: 0.5565290078520775
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
